#ifndef PUMPKINPLUGIN_GLOBAL_H
#define PUMPKINPLUGIN_GLOBAL_H

#if defined(PUMPKINPLUGIN_LIBRARY)
#  define PUMPKINPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define PUMPKINPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // PUMPKINPLUGIN_GLOBAL_H
